---
name: Testing

on:
  push:
    branches: [ master, v3 ]
  pull_request:
    branches: [ master, v3 ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod

      - name: Run tests
        if: success()
        run: go test -timeout 60s -cover ./... -coverprofile=coverage.txt -covermode=atomic
        env:
          PG_URI: "postgres://test:test@localhost:5432/test?sslmode=disable"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
